create table location (
	location_id INT,
	street_address VARCHAR(50),
	postal_code VARCHAR(50),
	city VARCHAR(50),
	state_province VARCHAR(50),
	country_id VARCHAR(50)
);
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (1, '1370 Northview Lane', '51715 CEDEX', 'Reims', 'Champagne-Ardenne', 'FR');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (2, '7633 Wayridge Terrace', null, '‘Ūrīf', null, 'PS');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (3, '04824 Raven Park', null, 'Kandangsapi', null, 'ID');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (4, '4652 Mayer Terrace', null, 'Progreso', null, 'PE');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (5, '893 Hudson Park', '2419', 'Patayac', null, 'PH');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (6, '16035 Crowley Lane', '33023', 'Hollywood', 'Florida', 'US');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (7, '3 Mcguire Circle', '733 24', 'Sala', 'Västmanland', 'SE');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (8, '50661 Eggendart Parkway', '132059', 'El Carmen de Bolívar', null, 'CO');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (9, '65883 Division Way', '4930-345', 'Calçada', 'Viana do Castelo', 'PT');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (10, '85048 Michigan Drive', null, 'Camilaca', null, 'PE');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (11, '05 Scoville Street', '31059 CEDEX 9', 'Toulouse', 'Midi-Pyrénées', 'FR');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (12, '0019 Mallory Center', null, 'Azogues', null, 'EC');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (13, '29895 Grim Hill', null, 'Shuitai', null, 'CN');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (14, '8058 Washington Plaza', null, 'Inčukalns', null, 'LV');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (15, '5 Bellgrove Park', null, 'Pombas', null, 'CV');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (16, '6303 6th Crossing', null, 'Ar Rujum', null, 'YE');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (17, '973 Farwell Hill', '8501', 'San Francisco', null, 'PH');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (18, '55844 Clarendon Avenue', '186806', 'Lyaskelya', null, 'RU');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (19, '0 Nevada Circle', '35252', 'Slobodnica', null, 'HR');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (20, '63 Saint Paul Court', null, 'Plataran', null, 'ID');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (21, '49 Green Road', null, 'La Peña', null, 'PA');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (22, '110 Marcy Hill', null, 'Kalangsari', null, 'ID');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (23, '3 Old Gate Terrace', null, 'Sambir', null, 'UA');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (24, '1 Londonderry Park', '94631 CEDEX 1', 'Rungis', 'Île-de-France', 'FR');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (25, '90124 Kinsman Terrace', '2410-505', 'Cortes', 'Leiria', 'PT');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (26, '93432 International Alley', null, 'Shani', null, 'NG');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (27, '83093 Rutledge Crossing', '42-270', 'Kłomnice', null, 'PL');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (28, '3 Eagan Center', null, 'Jiayi', null, 'CN');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (29, '7819 Fisk Terrace', '28904', 'Getafe', 'Madrid', 'ES');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (30, '8884 Huxley Parkway', null, 'Remas', null, 'AL');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (31, '59672 Spenser Plaza', '96310-000', 'Herval', null, 'BR');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (32, '25752 Laurel Way', '69639 CEDEX', 'Vénissieux', 'Rhône-Alpes', 'FR');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (33, '70101 Browning Center', '2005', 'Calangain', null, 'PH');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (34, '68 Bellgrove Plaza', null, 'Yuelai', null, 'CN');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (35, '517 Hintze Place', '55109 CEDEX', 'Verdun', 'Lorraine', 'FR');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (36, '61 Grim Hill', null, 'Gewanē', null, 'ET');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (37, '0736 Ohio Lane', '3525-355', 'Vale de Madeiros', 'Viseu', 'PT');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (38, '77 Pankratz Street', '4785-266', 'Paranho', 'Porto', 'PT');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (39, '02 Miller Circle', '89110-000', 'Gaspar', null, 'BR');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (40, '80129 Montana Center', null, 'Qaşr Hallāl', null, 'TN');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (41, '463 Barby Road', null, 'Zehak', null, 'IR');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (42, '7804 Rigney Road', null, 'Kilju', null, 'KP');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (43, '902 Longview Avenue', null, 'Wuxiang', null, 'CN');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (44, '8 Bonner Way', null, 'Tsaghkahovit', null, 'AM');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (45, '54 Scoville Junction', null, 'Tianhekou', null, 'CN');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (46, '10162 Nevada Trail', null, 'Nyangao', null, 'TZ');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (47, '69817 New Castle Junction', null, 'Upata', null, 'VE');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (48, '5099 Welch Terrace', '55928', 'Kuala Lumpur', 'Kuala Lumpur', 'MY');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (49, '43808 Mosinee Road', null, 'Nghi Xuân', null, 'VN');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (50, '812 Loftsgordon Terrace', null, 'Klevan’', null, 'UA');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (51, '4 Sage Point', null, 'Oodweyne', null, 'SO');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (52, '71750 Huxley Pass', null, 'Verkhniy Yasenov', null, 'UA');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (53, '6665 Melody Trail', null, 'Tiandu', null, 'CN');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (54, '59 Claremont Trail', null, 'Wanmingang', null, 'CN');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (55, '93653 Rockefeller Drive', '647462', 'Khatanga', null, 'RU');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (56, '8 6th Trail', '59895 CEDEX 9', 'Lille', 'Nord-Pas-de-Calais', 'FR');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (57, '0496 Bunker Hill Crossing', null, 'Al ‘Āliyah', null, 'TN');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (58, '2627 Huxley Way', null, 'Jorf', null, 'MA');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (59, '34 Bluejay Road', null, 'Apuri', null, 'ID');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (60, '95 Mariners Cove Trail', null, 'Melekyne', null, 'UA');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (61, '33211 Holmberg Hill', '253608', 'San Francisco', null, 'CO');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (62, '131 Brown Lane', '01905', 'Lynn', 'Massachusetts', 'US');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (63, '30652 Artisan Crossing', null, 'Pyu', null, 'MM');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (64, '38 Carpenter Drive', '195047', 'Florencia', null, 'CO');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (65, '3152 Lawn Crossing', '2422', 'Botao', null, 'PH');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (66, '978 Paget Circle', null, 'Tashkent', null, 'UZ');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (67, '9226 Russell Point', null, 'Fuyang', null, 'CN');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (68, '05 Spaight Avenue', null, 'Mulong', null, 'CN');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (69, '4196 Wayridge Parkway', '9704', 'Groningen', 'Provincie Groningen', 'NL');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (70, '686 Old Shore Lane', null, 'Krông Kmar', null, 'VN');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (71, '0 Merchant Street', null, 'Maradi', null, 'NE');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (72, '21655 Merrick Trail', '34-222', 'Grzechynia', null, 'PL');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (73, '46 Debs Park', null, 'Lanyang', null, 'CN');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (74, '28207 Lukken Plaza', '347460', 'Zimovniki', null, 'RU');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (75, '74780 Morning Center', '933 82', 'Arvidsjaur', 'Norrbotten', 'SE');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (76, '0 Corscot Street', null, 'Xieba', null, 'CN');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (77, '6 Dexter Center', null, 'Prilep', null, 'XK');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (78, '8 Oakridge Junction', null, 'Datarkadu', null, 'ID');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (79, '2282 Troy Alley', '4515-465', 'Melres', 'Porto', 'PT');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (80, '5040 Melody Pass', null, 'Numeto', null, 'ID');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (81, '4043 Ronald Regan Street', '26-307', 'Białaczów', null, 'PL');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (82, '3878 Gina Parkway', '42-244', 'Mstów', null, 'PL');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (83, '4180 Northridge Plaza', null, 'Budakovo', null, 'XK');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (84, '248 Stephen Circle', '68450-000', 'Moju', null, 'BR');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (85, '2 Warbler Junction', null, '‘Arīshah', null, 'SY');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (86, '3573 Old Shore Avenue', null, 'Ichuña', null, 'PE');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (87, '8 Lindbergh Plaza', '652 22', 'Karlstad', 'Värmland', 'SE');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (88, '993 Montana Avenue', '6415', 'San Roque', null, 'PH');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (89, '9800 Washington Terrace', '3050-300', 'Mealhada', 'Aveiro', 'PT');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (90, '23383 Pond Pass', null, 'Konggar', null, 'CN');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (91, '21 Loomis Parkway', null, 'Banjar Tengahbelayu', null, 'ID');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (92, '505 Petterle Plaza', '91965 CEDEX', 'Courtaboeuf', 'Île-de-France', 'FR');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (93, '51 Cottonwood Crossing', null, 'Xiaba', null, 'CN');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (94, '39 Marquette Way', null, 'Hantara', null, 'ID');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (95, '55619 Monument Hill', null, 'Bumirejo', null, 'ID');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (96, '357 Vidon Point', null, 'Nangewer', null, 'ID');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (97, '19062 Graceland Center', '45710-000', 'Itororó', null, 'BR');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (98, '198 Crownhardt Junction', '612730', 'Lesnyye Polyany', null, 'RU');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (99, '85182 Hovde Terrace', '32-503', 'Mętków', null, 'PL');
insert into location (location_id, street_address, postal_code, city, state_province, country_id) values (100, '8 Artisan Street', '3025-592', 'Costa de Rios Frios', 'Coimbra', 'PT');
