--SQL Exercises, Practice, Solution - Formatting Output


-- 1. From the following table, write a SQL query to select all the salespeople.
-- Return salesman_id, name, city, commission with the percent sign (%).

select * from salesman s ;

select salesman_id,name,city,commission || '%' "Commission" from salesman s ;

-- 2. From the following table, write a SQL query to find the 
-- number of orders booked for each day. Return the result in a format 
-- like "For 2001-10-10 there are 15 orders".". 

select * from orders o ;

select 'For' ,ord_date,'There Are',count(*),'Orders' from orders o
group by ord_date;



-- 3. From the following table, write a SQL query to find all the orders.
-- Sort the result-set in ascending order by ord_no. Return all fields. 

select * from orders o order by ord_no ;

-- 4. From the following table, write a SQL query to find all the orders.
-- Sort the result-set in descending order by ord_date. Return all fields.

select * from orders o order by ord_date desc;

-- 5. From the following table, write a SQL query to find all the orders. 
-- Sort the result-set in descending order by ord_date and purch_amt. Return all fields. 

select * from orders o order by ord_date desc ,purch_amt desc ;


-- 6. From the following table, write a SQL query to find all the customers.
-- Sort the result-set by customer_id. Return cust_name, city, grade. 

select * from customer c ;

select cust_name,city,grade from customer c order by customer_id ;

-- 7. From the following table, write a SQL query to calculate the maximum purchase
-- amount generated by each sales person for every order date. Sort the result-set
-- by sales person id and order date in ascending order. Return sales person id,
-- order date and maximum purchase amount.  

select * from orders o ;

select salesman_id,ord_date,max(purch_amt) from orders o 
group by ord_date,salesman_id order by salesman_id ,ord_date;


-- 8. From the following table, write a SQL query to find all the customers.
-- Sort the result-set in descending order on 3rd field. Return customer name,
-- city and grade.
select * from customer c ;

select cust_name,city,grade from customer c 
order by 3 desc ;


-- 9. From the following table, write a SQL query to count the unique orders, highest
-- purchase amount for each customer. Sort the result-set in descending order on 2nd field
-- . Return customer ID, number of distinct orders and highest 
-- purchase amount by each customer.

select * from orders o ;

select customer_id,count(distinct(ord_no)),max(purch_amt) from orders o 
group by customer_id order by 2 desc;

--Same Result
select customer_id,max(purch_amt) , count(distinct(ord_no)) from orders o 
group by customer_id order by 2 desc;


-- 10. From the following table, write a SQL query to calculate summation of
-- purchase amount, total commission (15% for all salesmen) by each order date.
-- Sort the result-set on order date. Return order date, summation of purchase amount
-- and commission.


select * from orders o ;

select ord_date,sum(purch_amt),sum(purch_amt)*0.15 "Commission" from orders o 
group by ord_date order by ord_date ;


