create table car (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	make VARCHAR(100) NOT NULL,
	model VARCHAR(100) NOT NULL,
	price INT NOT NULL
);
insert into car (id, make, model, price) values (1, 'Chevrolet', 'Cavalier', '4');
insert into car (id, make, model, price) values (2, 'Toyota', 'Celica', '368');
insert into car (id, make, model, price) values (3, 'Subaru', 'Legacy', '34');
insert into car (id, make, model, price) values (4, 'Bentley', 'Azure', '99');
insert into car (id, make, model, price) values (5, 'Honda', 'Insight', '46227');
insert into car (id, make, model, price) values (6, 'Lincoln', 'Mark LT', '44949');
insert into car (id, make, model, price) values (7, 'Ford', 'Escape', '20315');
insert into car (id, make, model, price) values (8, 'Suzuki', 'Grand Vitara', '5');
insert into car (id, make, model, price) values (9, 'Buick', 'LeSabre', '1');
insert into car (id, make, model, price) values (10, 'Chrysler', 'LHS', '2572');
insert into car (id, make, model, price) values (11, 'Geo', 'Metro', '30');
insert into car (id, make, model, price) values (12, 'Chevrolet', 'Caprice', '36353');
insert into car (id, make, model, price) values (13, 'Buick', 'Riviera', '9');
insert into car (id, make, model, price) values (14, 'Lexus', 'LS', '32');
insert into car (id, make, model, price) values (15, 'Saab', '9-5', '1810');
insert into car (id, make, model, price) values (16, 'Bentley', 'Continental GTC', '7362');
insert into car (id, make, model, price) values (17, 'Lexus', 'GS', '4541');
insert into car (id, make, model, price) values (18, 'Pontiac', 'Bonneville', '135');
insert into car (id, make, model, price) values (19, 'Ford', 'F-Series', '11306');
insert into car (id, make, model, price) values (20, 'Audi', '80', '967');
insert into car (id, make, model, price) values (21, 'Lexus', 'GS', '205');
insert into car (id, make, model, price) values (22, 'GMC', 'Vandura 3500', '576');
insert into car (id, make, model, price) values (23, 'Ford', 'Expedition', '38');
insert into car (id, make, model, price) values (24, 'Volkswagen', 'GTI', '3');
insert into car (id, make, model, price) values (25, 'Chevrolet', 'Colorado', '5');
insert into car (id, make, model, price) values (26, 'Mitsubishi', 'Galant', '34389');
insert into car (id, make, model, price) values (27, 'Ford', 'Escort', '15275');
insert into car (id, make, model, price) values (28, 'Volkswagen', 'Golf', '66207');
insert into car (id, make, model, price) values (29, 'Mitsubishi', 'Diamante', '3');
insert into car (id, make, model, price) values (30, 'BMW', '325', '9786');
insert into car (id, make, model, price) values (31, 'Infiniti', 'M', '636');
insert into car (id, make, model, price) values (32, 'Ford', 'F250', '9876');
insert into car (id, make, model, price) values (33, 'Toyota', 'Yaris', '35');
insert into car (id, make, model, price) values (34, 'Isuzu', 'Trooper', '45');
insert into car (id, make, model, price) values (35, 'Toyota', 'Venza', '39264');
insert into car (id, make, model, price) values (36, 'Lincoln', 'Mark VII', '49521');
insert into car (id, make, model, price) values (37, 'Mitsubishi', 'GTO', '4425');
insert into car (id, make, model, price) values (38, 'Mitsubishi', 'Challenger', '66');
insert into car (id, make, model, price) values (39, 'Ford', 'Crown Victoria', '00770');
insert into car (id, make, model, price) values (40, 'Mercury', 'Villager', '331');
insert into car (id, make, model, price) values (41, 'Dodge', 'Ram 3500', '4');
insert into car (id, make, model, price) values (42, 'Audi', 'A6', '537');
insert into car (id, make, model, price) values (43, 'Ford', 'Mustang', '575');
insert into car (id, make, model, price) values (44, 'Ford', 'Club Wagon', '94');
insert into car (id, make, model, price) values (45, 'Ford', 'F250', '013');
insert into car (id, make, model, price) values (46, 'Mitsubishi', 'Outlander', '12406');
insert into car (id, make, model, price) values (47, 'Ford', 'GT', '65789');
insert into car (id, make, model, price) values (48, 'Lexus', 'LS', '6500');
insert into car (id, make, model, price) values (49, 'GMC', 'Savana 2500', '8344');
insert into car (id, make, model, price) values (50, 'Volvo', '850', '45978');
insert into car (id, make, model, price) values (51, 'Jeep', 'Patriot', '1');
insert into car (id, make, model, price) values (52, 'Mazda', 'B-Series', '5');
insert into car (id, make, model, price) values (53, 'Isuzu', 'Hombre Space', '46222');
insert into car (id, make, model, price) values (54, 'Mitsubishi', 'Endeavor', '185');
insert into car (id, make, model, price) values (55, 'Buick', 'Regal', '4340');
insert into car (id, make, model, price) values (56, 'Lamborghini', 'Murciélago', '0');
insert into car (id, make, model, price) values (57, 'Nissan', 'Altima', '34607');
insert into car (id, make, model, price) values (58, 'GMC', '2500', '30814');
insert into car (id, make, model, price) values (59, 'GMC', 'Envoy', '80');
insert into car (id, make, model, price) values (60, 'Toyota', '4Runner', '63');
insert into car (id, make, model, price) values (61, 'Chevrolet', 'Express 1500', '20');
insert into car (id, make, model, price) values (62, 'Volkswagen', 'CC', '488');
insert into car (id, make, model, price) values (63, 'Buick', 'Skylark', '02');
insert into car (id, make, model, price) values (64, 'Suzuki', 'Sidekick', '4');
insert into car (id, make, model, price) values (65, 'Chevrolet', 'Blazer', '59407');
insert into car (id, make, model, price) values (66, 'Volvo', 'S40', '10');
insert into car (id, make, model, price) values (67, 'Chevrolet', 'Suburban 2500', '5647');
insert into car (id, make, model, price) values (68, 'BMW', '7 Series', '876');
insert into car (id, make, model, price) values (69, 'Pontiac', 'Sunfire', '2');
insert into car (id, make, model, price) values (70, 'GMC', 'Sierra', '2');
insert into car (id, make, model, price) values (71, 'GMC', 'Sierra', '7134');
insert into car (id, make, model, price) values (72, 'BMW', 'X5', '9415');
insert into car (id, make, model, price) values (73, 'Dodge', 'D150', '6308');
insert into car (id, make, model, price) values (74, 'BMW', '5 Series', '23364');
insert into car (id, make, model, price) values (75, 'Volkswagen', 'Corrado', '9007');
insert into car (id, make, model, price) values (76, 'Lotus', 'Elise', '99663');
insert into car (id, make, model, price) values (77, 'Mercury', 'Grand Marquis', '6806');
insert into car (id, make, model, price) values (78, 'Chevrolet', 'Suburban 1500', '319');
insert into car (id, make, model, price) values (79, 'Cadillac', 'Escalade ESV', '94');
insert into car (id, make, model, price) values (80, 'Saab', '900', '6210');
insert into car (id, make, model, price) values (81, 'Mercury', 'Cougar', '1900');
insert into car (id, make, model, price) values (82, 'Lexus', 'GX', '5');
insert into car (id, make, model, price) values (83, 'Ford', 'GT500', '4507');
insert into car (id, make, model, price) values (84, 'Chevrolet', 'Equinox', '74');
insert into car (id, make, model, price) values (85, 'Suzuki', 'SJ', '44301');
insert into car (id, make, model, price) values (86, 'Cadillac', 'Escalade', '10154');
insert into car (id, make, model, price) values (87, 'Mazda', 'MX-5', '89669');
insert into car (id, make, model, price) values (88, 'Cadillac', 'STS', '30933');
insert into car (id, make, model, price) values (89, 'Chevrolet', 'TrailBlazer', '3330');
insert into car (id, make, model, price) values (90, 'Lexus', 'GS', '85');
insert into car (id, make, model, price) values (91, 'Suzuki', 'Aerio', '279');
insert into car (id, make, model, price) values (92, 'Toyota', 'Paseo', '65947');
insert into car (id, make, model, price) values (93, 'GMC', 'Safari', '94');
insert into car (id, make, model, price) values (94, 'Mazda', 'Mazda5', '25430');
insert into car (id, make, model, price) values (95, 'Toyota', 'Sequoia', '0576');
insert into car (id, make, model, price) values (96, 'Porsche', '928', '096');
insert into car (id, make, model, price) values (97, 'Rolls-Royce', 'Phantom', '284');
insert into car (id, make, model, price) values (98, 'Saab', '9-5', '55');
insert into car (id, make, model, price) values (99, 'Mazda', 'RX-7', '9');
insert into car (id, make, model, price) values (100, 'Oldsmobile', 'Cutlass Supreme', '1913');
insert into car (id, make, model, price) values (101, 'Oldsmobile', '88', '0854');
insert into car (id, make, model, price) values (102, 'Saab', '900', '411');
insert into car (id, make, model, price) values (103, 'Toyota', 'Camry', '9');
insert into car (id, make, model, price) values (104, 'Ford', 'F250', '6568');
insert into car (id, make, model, price) values (105, 'GMC', 'Savana', '6');
insert into car (id, make, model, price) values (106, 'Ford', 'Festiva', '53996');
insert into car (id, make, model, price) values (107, 'Volkswagen', 'Passat', '6');
insert into car (id, make, model, price) values (108, 'Honda', 'Accord', '93657');
insert into car (id, make, model, price) values (109, 'Cadillac', 'Eldorado', '5126');
insert into car (id, make, model, price) values (110, 'Dodge', 'Avenger', '5749');
insert into car (id, make, model, price) values (111, 'Chevrolet', 'Suburban 1500', '8');
insert into car (id, make, model, price) values (112, 'BMW', '5 Series', '3');
insert into car (id, make, model, price) values (113, 'Toyota', 'FJ Cruiser', '9');
insert into car (id, make, model, price) values (114, 'Ford', 'Fusion', '4');
insert into car (id, make, model, price) values (115, 'Hyundai', 'Sonata', '391');
insert into car (id, make, model, price) values (116, 'GMC', 'Sierra 3500', '33029');
insert into car (id, make, model, price) values (117, 'Volvo', 'S80', '2');
insert into car (id, make, model, price) values (118, 'Mercedes-Benz', 'E-Class', '81627');
insert into car (id, make, model, price) values (119, 'Acura', 'RSX', '055');
insert into car (id, make, model, price) values (120, 'Ferrari', '458 Italia', '53');
insert into car (id, make, model, price) values (121, 'Volkswagen', 'Scirocco', '70');
insert into car (id, make, model, price) values (122, 'Ford', 'LTD Crown Victoria', '42684');
insert into car (id, make, model, price) values (123, 'Audi', 'TT', '4');
insert into car (id, make, model, price) values (124, 'Honda', 'Insight', '0557');
insert into car (id, make, model, price) values (125, 'Porsche', '928', '4');
insert into car (id, make, model, price) values (126, 'Jeep', 'Cherokee', '65651');
insert into car (id, make, model, price) values (127, 'Toyota', 'Matrix', '772');
insert into car (id, make, model, price) values (128, 'Suzuki', 'Sidekick', '7906');
insert into car (id, make, model, price) values (129, 'Mercury', 'Mountaineer', '011');
insert into car (id, make, model, price) values (130, 'Lexus', 'RX', '7');
insert into car (id, make, model, price) values (131, 'Nissan', '300ZX', '3272');
insert into car (id, make, model, price) values (132, 'Audi', 'A8', '9193');
insert into car (id, make, model, price) values (133, 'Dodge', 'Dakota Club', '97491');
insert into car (id, make, model, price) values (134, 'Volkswagen', 'Scirocco', '02');
insert into car (id, make, model, price) values (135, 'Jeep', 'Liberty', '71921');
insert into car (id, make, model, price) values (136, 'Lamborghini', 'Gallardo', '02');
insert into car (id, make, model, price) values (137, 'Hummer', 'H1', '0');
insert into car (id, make, model, price) values (138, 'Toyota', 'Sienna', '87254');
insert into car (id, make, model, price) values (139, 'Mercedes-Benz', 'M-Class', '91');
insert into car (id, make, model, price) values (140, 'Acura', 'RL', '867');
insert into car (id, make, model, price) values (141, 'Oldsmobile', 'Bravada', '086');
insert into car (id, make, model, price) values (142, 'Toyota', 'Tacoma', '64654');
insert into car (id, make, model, price) values (143, 'Hyundai', 'Tiburon', '6754');
insert into car (id, make, model, price) values (144, 'Honda', 'Civic Si', '5669');
insert into car (id, make, model, price) values (145, 'Chevrolet', 'Silverado', '76');
insert into car (id, make, model, price) values (146, 'Toyota', 'Corolla', '07359');
insert into car (id, make, model, price) values (147, 'Buick', 'Riviera', '55');
insert into car (id, make, model, price) values (148, 'Lincoln', 'Mark VIII', '50');
insert into car (id, make, model, price) values (149, 'Pontiac', 'Grand Prix', '0792');
insert into car (id, make, model, price) values (150, 'Buick', 'Rainier', '68');
insert into car (id, make, model, price) values (151, 'Plymouth', 'Laser', '57333');
insert into car (id, make, model, price) values (152, 'Dodge', 'Colt', '1');
insert into car (id, make, model, price) values (153, 'Ford', 'Bronco', '6434');
insert into car (id, make, model, price) values (154, 'Lincoln', 'Town Car', '6495');
insert into car (id, make, model, price) values (155, 'BMW', 'X6', '903');
insert into car (id, make, model, price) values (156, 'Volvo', 'V70', '2712');
insert into car (id, make, model, price) values (157, 'Toyota', 'Land Cruiser', '558');
insert into car (id, make, model, price) values (158, 'Mitsubishi', 'Expo', '8');
insert into car (id, make, model, price) values (159, 'Cadillac', 'STS-V', '84');
insert into car (id, make, model, price) values (160, 'Buick', 'Skyhawk', '39589');
insert into car (id, make, model, price) values (161, 'Acura', 'TL', '1');
insert into car (id, make, model, price) values (162, 'Toyota', 'Avalon', '582');
insert into car (id, make, model, price) values (163, 'Mercury', 'Grand Marquis', '18957');
insert into car (id, make, model, price) values (164, 'Pontiac', 'LeMans', '99');
insert into car (id, make, model, price) values (165, 'Chevrolet', 'Malibu', '81615');
insert into car (id, make, model, price) values (166, 'Lincoln', 'Town Car', '3133');
insert into car (id, make, model, price) values (167, 'Cadillac', 'DeVille', '63541');
insert into car (id, make, model, price) values (168, 'Chevrolet', 'Suburban 2500', '234');
insert into car (id, make, model, price) values (169, 'Mercedes-Benz', '300SL', '23');
insert into car (id, make, model, price) values (170, 'Plymouth', 'Colt Vista', '9690');
insert into car (id, make, model, price) values (171, 'Chrysler', 'Sebring', '2');
insert into car (id, make, model, price) values (172, 'Infiniti', 'FX', '271');
insert into car (id, make, model, price) values (173, 'GMC', 'Savana 1500', '9349');
insert into car (id, make, model, price) values (174, 'Pontiac', 'GTO', '5093');
insert into car (id, make, model, price) values (175, 'Suzuki', 'Cultus', '11030');
insert into car (id, make, model, price) values (176, 'Eagle', 'Vision', '00946');
insert into car (id, make, model, price) values (177, 'Mitsubishi', 'Montero', '35647');
insert into car (id, make, model, price) values (178, 'Jaguar', 'X-Type', '89');
insert into car (id, make, model, price) values (179, 'Honda', 'Accord', '77');
insert into car (id, make, model, price) values (180, 'Volkswagen', 'GTI', '8573');
insert into car (id, make, model, price) values (181, 'Land Rover', 'Range Rover', '07673');
insert into car (id, make, model, price) values (182, 'BMW', '530', '9');
insert into car (id, make, model, price) values (183, 'Subaru', 'Outback', '83232');
insert into car (id, make, model, price) values (184, 'Nissan', 'Altima', '5455');
insert into car (id, make, model, price) values (185, 'Dodge', 'D350 Club', '62259');
insert into car (id, make, model, price) values (186, 'Volkswagen', 'New Beetle', '2');
insert into car (id, make, model, price) values (187, 'Dodge', 'Ram 2500', '4848');
insert into car (id, make, model, price) values (188, 'Mazda', '626', '4392');
insert into car (id, make, model, price) values (189, 'Mitsubishi', 'Montero', '0915');
insert into car (id, make, model, price) values (190, 'Chevrolet', 'Suburban 2500', '036');
insert into car (id, make, model, price) values (191, 'Audi', '4000s Quattro', '18267');
insert into car (id, make, model, price) values (192, 'Saab', '9-3', '085');
insert into car (id, make, model, price) values (193, 'Honda', 'Civic', '112');
insert into car (id, make, model, price) values (194, 'Chevrolet', 'Corvette', '416');
insert into car (id, make, model, price) values (195, 'Toyota', 'Matrix', '8');
insert into car (id, make, model, price) values (196, 'Volkswagen', 'Cabriolet', '7183');
insert into car (id, make, model, price) values (197, 'Lincoln', 'Continental', '9196');
insert into car (id, make, model, price) values (198, 'Kia', 'Sedona', '30031');
insert into car (id, make, model, price) values (199, 'Dodge', 'Ram Van B150', '69');
insert into car (id, make, model, price) values (200, 'Audi', 'A4', '0653');
insert into car (id, make, model, price) values (201, 'Suzuki', 'Esteem', '932');
insert into car (id, make, model, price) values (202, 'Pontiac', 'Parisienne', '56');
insert into car (id, make, model, price) values (203, 'Ford', 'F350', '33');
insert into car (id, make, model, price) values (204, 'Land Rover', 'Range Rover', '43086');
insert into car (id, make, model, price) values (205, 'Jeep', 'Liberty', '26519');
insert into car (id, make, model, price) values (206, 'Chevrolet', 'Cobalt', '93');
insert into car (id, make, model, price) values (207, 'Dodge', 'Caliber', '5');
insert into car (id, make, model, price) values (208, 'Acura', 'TL', '39');
insert into car (id, make, model, price) values (209, 'Saab', '9-3', '2');
insert into car (id, make, model, price) values (210, 'Lexus', 'LS', '66259');
insert into car (id, make, model, price) values (211, 'Infiniti', 'QX56', '3798');
insert into car (id, make, model, price) values (212, 'Pontiac', 'Grand Prix', '4');
insert into car (id, make, model, price) values (213, 'Lotus', 'Elise', '7');
insert into car (id, make, model, price) values (214, 'BMW', 'X5', '81');
insert into car (id, make, model, price) values (215, 'Mercedes-Benz', 'S-Class', '19');
insert into car (id, make, model, price) values (216, 'Oldsmobile', 'Alero', '48962');
insert into car (id, make, model, price) values (217, 'Mercedes-Benz', 'SL-Class', '5008');
insert into car (id, make, model, price) values (218, 'Pontiac', 'Bonneville', '27');
insert into car (id, make, model, price) values (219, 'Mitsubishi', 'RVR', '2');
insert into car (id, make, model, price) values (220, 'Pontiac', 'G5', '4');
insert into car (id, make, model, price) values (221, 'Suzuki', 'Verona', '5347');
insert into car (id, make, model, price) values (222, 'Dodge', 'Neon', '8688');
insert into car (id, make, model, price) values (223, 'Mercedes-Benz', 'SLR McLaren', '2559');
insert into car (id, make, model, price) values (224, 'Volvo', 'C70', '9');
insert into car (id, make, model, price) values (225, 'Chevrolet', 'Suburban 1500', '5');
insert into car (id, make, model, price) values (226, 'Cadillac', 'Catera', '937');
insert into car (id, make, model, price) values (227, 'Chevrolet', 'Corvette', '94');
insert into car (id, make, model, price) values (228, 'Volkswagen', 'rio', '7');
insert into car (id, make, model, price) values (229, 'Chevrolet', 'SSR', '024');
insert into car (id, make, model, price) values (230, 'Acura', 'TSX', '7147');
insert into car (id, make, model, price) values (231, 'Buick', 'Century', '2939');
insert into car (id, make, model, price) values (232, 'Audi', 'TT', '3946');
insert into car (id, make, model, price) values (233, 'Mazda', 'Miata MX-5', '41');
insert into car (id, make, model, price) values (234, 'Toyota', 'Echo', '0');
insert into car (id, make, model, price) values (235, 'Toyota', 'Tundra', '4567');
insert into car (id, make, model, price) values (236, 'Honda', 'Passport', '99');
insert into car (id, make, model, price) values (237, 'Mitsubishi', 'Diamante', '7');
insert into car (id, make, model, price) values (238, 'Buick', 'Park Avenue', '4473');
insert into car (id, make, model, price) values (239, 'Mitsubishi', 'Pajero', '0118');
insert into car (id, make, model, price) values (240, 'Mercedes-Benz', 'SL-Class', '7755');
insert into car (id, make, model, price) values (241, 'Mazda', 'Mazda5', '79');
insert into car (id, make, model, price) values (242, 'Plymouth', 'Roadrunner', '4');
insert into car (id, make, model, price) values (243, 'Ford', 'F-Series', '1123');
insert into car (id, make, model, price) values (244, 'Honda', 'Civic', '47');
insert into car (id, make, model, price) values (245, 'Buick', 'Regal', '37327');
insert into car (id, make, model, price) values (246, 'Mercury', 'Mystique', '44249');
insert into car (id, make, model, price) values (247, 'Toyota', 'Camry', '741');
insert into car (id, make, model, price) values (248, 'Volkswagen', 'New Beetle', '64');
insert into car (id, make, model, price) values (249, 'Porsche', '911', '9');
insert into car (id, make, model, price) values (250, 'Ford', 'F350', '0');
insert into car (id, make, model, price) values (251, 'Mitsubishi', 'RVR', '99950');
insert into car (id, make, model, price) values (252, 'Buick', 'Park Avenue', '44');
insert into car (id, make, model, price) values (253, 'Dodge', 'Ram Van B350', '0458');
insert into car (id, make, model, price) values (254, 'Infiniti', 'G', '91');
insert into car (id, make, model, price) values (255, 'Cadillac', 'Escalade EXT', '9');
insert into car (id, make, model, price) values (256, 'Subaru', 'Leone', '62574');
insert into car (id, make, model, price) values (257, 'Nissan', 'Rogue', '8');
insert into car (id, make, model, price) values (258, 'GMC', 'Jimmy', '11444');
insert into car (id, make, model, price) values (259, 'Lincoln', 'Town Car', '1');
insert into car (id, make, model, price) values (260, 'Dodge', 'Viper', '8635');
insert into car (id, make, model, price) values (261, 'Mazda', 'MPV', '3175');
insert into car (id, make, model, price) values (262, 'Chevrolet', 'Blazer', '0');
insert into car (id, make, model, price) values (263, 'Jeep', 'Wrangler', '0925');
insert into car (id, make, model, price) values (264, 'Volvo', 'S60', '58665');
insert into car (id, make, model, price) values (265, 'Pontiac', 'Sunbird', '25');
insert into car (id, make, model, price) values (266, 'Lexus', 'IS', '84848');
insert into car (id, make, model, price) values (267, 'Volkswagen', 'rio', '93');
insert into car (id, make, model, price) values (268, 'GMC', 'Envoy XL', '8563');
insert into car (id, make, model, price) values (269, 'Toyota', 'Corolla', '3016');
insert into car (id, make, model, price) values (270, 'Ford', 'E-350 Super Duty', '49');
insert into car (id, make, model, price) values (271, 'Ford', 'Ranger', '3');
insert into car (id, make, model, price) values (272, 'Ford', 'Flex', '21');
insert into car (id, make, model, price) values (273, 'Mazda', 'MPV', '82');
insert into car (id, make, model, price) values (274, 'Dodge', 'Avenger', '5');
insert into car (id, make, model, price) values (275, 'Buick', 'Enclave', '6131');
insert into car (id, make, model, price) values (276, 'Land Rover', 'Defender Ice Edition', '48');
insert into car (id, make, model, price) values (277, 'Ford', 'Escort', '447');
insert into car (id, make, model, price) values (278, 'Chevrolet', 'Monte Carlo', '71');
insert into car (id, make, model, price) values (279, 'Honda', 'Prelude', '23');
insert into car (id, make, model, price) values (280, 'Chevrolet', 'Camaro', '9');
insert into car (id, make, model, price) values (281, 'Buick', 'Skylark', '16809');
insert into car (id, make, model, price) values (282, 'Mazda', 'Familia', '34');
insert into car (id, make, model, price) values (283, 'Ford', 'F250', '220');
insert into car (id, make, model, price) values (284, 'BMW', 'M Roadster', '9523');
insert into car (id, make, model, price) values (285, 'Honda', 'CR-V', '500');
insert into car (id, make, model, price) values (286, 'Pontiac', 'Bonneville', '11');
insert into car (id, make, model, price) values (287, 'Jeep', 'Grand Cherokee', '40068');
insert into car (id, make, model, price) values (288, 'Jaguar', 'XK', '92');
insert into car (id, make, model, price) values (289, 'Buick', 'Century', '25');
insert into car (id, make, model, price) values (290, 'Hyundai', 'Genesis Coupe', '27');
insert into car (id, make, model, price) values (291, 'Buick', 'Enclave', '39354');
insert into car (id, make, model, price) values (292, 'Chrysler', 'Pacifica', '388');
insert into car (id, make, model, price) values (293, 'Maserati', '430', '56');
insert into car (id, make, model, price) values (294, 'Mercury', 'Villager', '2247');
insert into car (id, make, model, price) values (295, 'Hyundai', 'Equus', '31272');
insert into car (id, make, model, price) values (296, 'Subaru', 'Legacy', '41753');
insert into car (id, make, model, price) values (297, 'Eagle', 'Talon', '370');
insert into car (id, make, model, price) values (298, 'Mitsubishi', 'Challenger', '4735');
insert into car (id, make, model, price) values (299, 'Mazda', 'Mazda6 Sport', '42939');
insert into car (id, make, model, price) values (300, 'Ford', 'F150', '54');
insert into car (id, make, model, price) values (301, 'Lamborghini', 'Countach', '92');
insert into car (id, make, model, price) values (302, 'Isuzu', 'Stylus', '596');
insert into car (id, make, model, price) values (303, 'Mercury', 'Mountaineer', '93227');
insert into car (id, make, model, price) values (304, 'Chevrolet', 'Cavalier', '432');
insert into car (id, make, model, price) values (305, 'Chevrolet', 'Lumina', '6094');
insert into car (id, make, model, price) values (306, 'Chevrolet', '1500', '7780');
insert into car (id, make, model, price) values (307, 'Hyundai', 'Genesis Coupe', '11');
insert into car (id, make, model, price) values (308, 'Mercedes-Benz', 'SL-Class', '23938');
insert into car (id, make, model, price) values (309, 'Dodge', 'Caliber', '38218');
insert into car (id, make, model, price) values (310, 'Mercedes-Benz', 'M-Class', '818');
insert into car (id, make, model, price) values (311, 'Chevrolet', '1500', '598');
insert into car (id, make, model, price) values (312, 'Subaru', 'Legacy', '7448');
insert into car (id, make, model, price) values (313, 'Chevrolet', 'Cobalt SS', '70361');
insert into car (id, make, model, price) values (314, 'Jaguar', 'XJ', '307');
insert into car (id, make, model, price) values (315, 'Toyota', 'Sequoia', '24');
insert into car (id, make, model, price) values (316, 'Chevrolet', '3500', '5');
insert into car (id, make, model, price) values (317, 'Mitsubishi', 'Outlander Sport', '7768');
insert into car (id, make, model, price) values (318, 'Mercury', 'Grand Marquis', '418');
insert into car (id, make, model, price) values (319, 'GMC', 'Sierra 1500', '4373');
insert into car (id, make, model, price) values (320, 'Aptera', 'Type-1h', '127');
insert into car (id, make, model, price) values (321, 'Ford', 'Explorer Sport Trac', '396');
insert into car (id, make, model, price) values (322, 'Mercedes-Benz', 'M-Class', '1');
insert into car (id, make, model, price) values (323, 'Lincoln', 'Mark LT', '11');
insert into car (id, make, model, price) values (324, 'Pontiac', 'Safari', '74');
insert into car (id, make, model, price) values (325, 'Chevrolet', 'SSR', '69740');
insert into car (id, make, model, price) values (326, 'Chevrolet', 'Impala', '47');
insert into car (id, make, model, price) values (327, 'Pontiac', 'Grand Prix', '9');
insert into car (id, make, model, price) values (328, 'Lexus', 'SC', '085');
insert into car (id, make, model, price) values (329, 'Hummer', 'H1', '781');
insert into car (id, make, model, price) values (330, 'Oldsmobile', 'Alero', '531');
insert into car (id, make, model, price) values (331, 'Chevrolet', 'Silverado 2500', '1267');
insert into car (id, make, model, price) values (332, 'Land Rover', 'Discovery', '766');
insert into car (id, make, model, price) values (333, 'Acura', 'Integra', '8740');
insert into car (id, make, model, price) values (334, 'Cadillac', 'Sixty Special', '582');
insert into car (id, make, model, price) values (335, 'Mercury', 'Lynx', '1339');
insert into car (id, make, model, price) values (336, 'Buick', 'Skylark', '21442');
insert into car (id, make, model, price) values (337, 'Mercury', 'Montego', '20');
insert into car (id, make, model, price) values (338, 'GMC', 'Sierra 3500', '2');
insert into car (id, make, model, price) values (339, 'Chevrolet', 'Tahoe', '2');
insert into car (id, make, model, price) values (340, 'Volkswagen', 'New Beetle', '88');
insert into car (id, make, model, price) values (341, 'Oldsmobile', 'Achieva', '7');
insert into car (id, make, model, price) values (342, 'Dodge', 'Journey', '06');
insert into car (id, make, model, price) values (343, 'Acura', 'NSX', '2259');
insert into car (id, make, model, price) values (344, 'Porsche', '911', '38468');
insert into car (id, make, model, price) values (345, 'Pontiac', 'LeMans', '8');
insert into car (id, make, model, price) values (346, 'Mitsubishi', 'Cordia', '0822');
insert into car (id, make, model, price) values (347, 'Mercedes-Benz', 'SL-Class', '569');
insert into car (id, make, model, price) values (348, 'Aston Martin', 'Rapide', '3');
insert into car (id, make, model, price) values (349, 'Suzuki', 'Swift', '75485');
insert into car (id, make, model, price) values (350, 'Chevrolet', 'Traverse', '81');
insert into car (id, make, model, price) values (351, 'Honda', 'Odyssey', '2');
insert into car (id, make, model, price) values (352, 'Suzuki', 'SJ', '81');
insert into car (id, make, model, price) values (353, 'Ford', 'Laser', '08900');
insert into car (id, make, model, price) values (354, 'Chevrolet', 'Venture', '214');
insert into car (id, make, model, price) values (355, 'Mercedes-Benz', 'W123', '596');
insert into car (id, make, model, price) values (356, 'Jeep', 'Liberty', '95');
insert into car (id, make, model, price) values (357, 'Buick', 'Rendezvous', '85');
insert into car (id, make, model, price) values (358, 'Ford', 'Crown Victoria', '69');
insert into car (id, make, model, price) values (359, 'Dodge', 'Stratus', '08');
insert into car (id, make, model, price) values (360, 'Ford', 'F350', '385');
insert into car (id, make, model, price) values (361, 'Mazda', 'Tribute', '732');
insert into car (id, make, model, price) values (362, 'Rambler', 'Classic', '905');
insert into car (id, make, model, price) values (363, 'Nissan', 'Murano', '0');
insert into car (id, make, model, price) values (364, 'Hyundai', 'Accent', '72836');
insert into car (id, make, model, price) values (365, 'Chevrolet', 'Express 1500', '83521');
insert into car (id, make, model, price) values (366, 'Mazda', 'Millenia', '7');
insert into car (id, make, model, price) values (367, 'BMW', 'Z4', '2921');
insert into car (id, make, model, price) values (368, 'Mazda', 'Mazda3', '0144');
insert into car (id, make, model, price) values (369, 'Acura', 'RDX', '55214');
insert into car (id, make, model, price) values (370, 'GMC', 'Envoy XUV', '2713');
insert into car (id, make, model, price) values (371, 'Chevrolet', 'Impala', '96');
insert into car (id, make, model, price) values (372, 'Mitsubishi', 'Truck', '050');
insert into car (id, make, model, price) values (373, 'Chevrolet', 'Uplander', '390');
insert into car (id, make, model, price) values (374, 'Mitsubishi', 'Mirage', '7314');
insert into car (id, make, model, price) values (375, 'Pontiac', 'GTO', '507');
insert into car (id, make, model, price) values (376, 'Porsche', '911', '41');
insert into car (id, make, model, price) values (377, 'BMW', 'M3', '9');
insert into car (id, make, model, price) values (378, 'Mitsubishi', 'Pajero', '37');
insert into car (id, make, model, price) values (379, 'Mitsubishi', 'Mirage', '87567');
insert into car (id, make, model, price) values (380, 'Volkswagen', 'Eurovan', '3');
insert into car (id, make, model, price) values (381, 'Dodge', 'Ram 3500', '377');
insert into car (id, make, model, price) values (382, 'Kia', 'Sportage', '686');
insert into car (id, make, model, price) values (383, 'Ford', 'F-Series', '52721');
insert into car (id, make, model, price) values (384, 'Subaru', 'Impreza', '90683');
insert into car (id, make, model, price) values (385, 'Saturn', 'VUE', '29305');
insert into car (id, make, model, price) values (386, 'Nissan', 'Frontier', '3');
insert into car (id, make, model, price) values (387, 'Ford', 'Ranger', '28');
insert into car (id, make, model, price) values (388, 'Land Rover', 'Discovery', '4509');
insert into car (id, make, model, price) values (389, 'Mercury', 'Grand Marquis', '162');
insert into car (id, make, model, price) values (390, 'Buick', 'Regal', '1467');
insert into car (id, make, model, price) values (391, 'Land Rover', 'Discovery Series II', '3');
insert into car (id, make, model, price) values (392, 'Nissan', 'NX', '4624');
insert into car (id, make, model, price) values (393, 'Land Rover', 'Discovery', '569');
insert into car (id, make, model, price) values (394, 'Ford', 'Econoline E350', '0762');
insert into car (id, make, model, price) values (395, 'Lexus', 'IS', '010');
insert into car (id, make, model, price) values (396, 'Oldsmobile', 'Alero', '10');
insert into car (id, make, model, price) values (397, 'Ford', 'Edge', '79085');
insert into car (id, make, model, price) values (398, 'Mazda', 'MPV', '1');
insert into car (id, make, model, price) values (399, 'Chrysler', 'Town & Country', '929');
insert into car (id, make, model, price) values (400, 'Saab', '9-5', '51');
insert into car (id, make, model, price) values (401, 'Nissan', 'Quest', '7');
insert into car (id, make, model, price) values (402, 'Lamborghini', 'Diablo', '81');
insert into car (id, make, model, price) values (403, 'Buick', 'Century', '3694');
insert into car (id, make, model, price) values (404, 'Mazda', 'RX-8', '46176');
insert into car (id, make, model, price) values (405, 'Jaguar', 'XJ Series', '486');
insert into car (id, make, model, price) values (406, 'Chevrolet', 'Express 2500', '04954');
insert into car (id, make, model, price) values (407, 'Chevrolet', 'Tahoe', '5');
insert into car (id, make, model, price) values (408, 'Nissan', 'Quest', '38');
insert into car (id, make, model, price) values (409, 'Lincoln', 'Town Car', '4236');
insert into car (id, make, model, price) values (410, 'Mitsubishi', 'Montero', '7');
insert into car (id, make, model, price) values (411, 'Toyota', 'Land Cruiser', '55');
insert into car (id, make, model, price) values (412, 'Mercedes-Benz', '500SEC', '92');
insert into car (id, make, model, price) values (413, 'Nissan', 'Versa', '41');
insert into car (id, make, model, price) values (414, 'Isuzu', 'Trooper', '8');
insert into car (id, make, model, price) values (415, 'Chevrolet', 'Caprice', '6984');
insert into car (id, make, model, price) values (416, 'Chevrolet', 'Camaro', '7066');
insert into car (id, make, model, price) values (417, 'Chrysler', 'Sebring', '2951');
insert into car (id, make, model, price) values (418, 'Mazda', 'CX-9', '745');
insert into car (id, make, model, price) values (419, 'Audi', 'A6', '7302');
insert into car (id, make, model, price) values (420, 'Ford', 'Crown Victoria', '38986');
insert into car (id, make, model, price) values (421, 'Mercedes-Benz', 'SLR McLaren', '2');
insert into car (id, make, model, price) values (422, 'Ford', 'Econoline E150', '883');
insert into car (id, make, model, price) values (423, 'GMC', 'Envoy', '2');
insert into car (id, make, model, price) values (424, 'Mazda', '929', '001');
insert into car (id, make, model, price) values (425, 'Toyota', 'Corolla', '35629');
insert into car (id, make, model, price) values (426, 'Pontiac', 'Sunfire', '007');
insert into car (id, make, model, price) values (427, 'Toyota', 'Solara', '1697');
insert into car (id, make, model, price) values (428, 'Buick', 'LeSabre', '7736');
insert into car (id, make, model, price) values (429, 'Cadillac', 'STS', '17');
insert into car (id, make, model, price) values (430, 'Eagle', 'Talon', '43343');
insert into car (id, make, model, price) values (431, 'Hyundai', 'Genesis Coupe', '7891');
insert into car (id, make, model, price) values (432, 'GMC', 'Sonoma Club', '13846');
insert into car (id, make, model, price) values (433, 'Ferrari', 'F430', '24');
insert into car (id, make, model, price) values (434, 'Ford', 'F150', '42653');
insert into car (id, make, model, price) values (435, 'Hyundai', 'Tucson', '8943');
insert into car (id, make, model, price) values (436, 'Dodge', 'Shadow', '4');
insert into car (id, make, model, price) values (437, 'Ferrari', 'California', '03036');
insert into car (id, make, model, price) values (438, 'Volkswagen', 'rio', '68');
insert into car (id, make, model, price) values (439, 'Porsche', 'Cayman', '375');
insert into car (id, make, model, price) values (440, 'Toyota', 'Land Cruiser', '5');
insert into car (id, make, model, price) values (441, 'Nissan', '240SX', '21410');
insert into car (id, make, model, price) values (442, 'Cadillac', 'Fleetwood', '35084');
insert into car (id, make, model, price) values (443, 'Mercury', 'Mystique', '23');
insert into car (id, make, model, price) values (444, 'Acura', 'CL', '98');
insert into car (id, make, model, price) values (445, 'Suzuki', 'Vitara', '9372');
insert into car (id, make, model, price) values (446, 'Ford', 'F-Series Super Duty', '53115');
insert into car (id, make, model, price) values (447, 'Volvo', 'C70', '1947');
insert into car (id, make, model, price) values (448, 'Isuzu', 'Trooper', '11');
insert into car (id, make, model, price) values (449, 'Audi', 'Coupe GT', '91633');
insert into car (id, make, model, price) values (450, 'Pontiac', 'Grand Prix', '500');
insert into car (id, make, model, price) values (451, 'Lincoln', 'MKS', '1');
insert into car (id, make, model, price) values (452, 'Mitsubishi', 'Eclipse', '20834');
insert into car (id, make, model, price) values (453, 'MINI', 'Cooper Countryman', '84');
insert into car (id, make, model, price) values (454, 'Hyundai', 'Veloster', '345');
insert into car (id, make, model, price) values (455, 'Honda', 'Prelude', '4058');
insert into car (id, make, model, price) values (456, 'Lincoln', 'Navigator L', '16096');
insert into car (id, make, model, price) values (457, 'Mitsubishi', 'Excel', '20978');
insert into car (id, make, model, price) values (458, 'Subaru', 'Outback', '6948');
insert into car (id, make, model, price) values (459, 'Dodge', 'Ram Van 1500', '81');
insert into car (id, make, model, price) values (460, 'Ford', 'Ranger', '81');
insert into car (id, make, model, price) values (461, 'GMC', 'Savana', '31126');
insert into car (id, make, model, price) values (462, 'Ford', 'F-Series', '6485');
insert into car (id, make, model, price) values (463, 'Toyota', 'Celica', '758');
insert into car (id, make, model, price) values (464, 'Nissan', 'Altima', '72');
insert into car (id, make, model, price) values (465, 'GMC', 'Acadia', '7');
insert into car (id, make, model, price) values (466, 'BMW', 'X5', '381');
insert into car (id, make, model, price) values (467, 'Dodge', 'Viper', '6');
insert into car (id, make, model, price) values (468, 'Pontiac', 'Bonneville', '559');
insert into car (id, make, model, price) values (469, 'Isuzu', 'Rodeo', '89805');
insert into car (id, make, model, price) values (470, 'Ford', 'Escape', '74');
insert into car (id, make, model, price) values (471, 'Toyota', 'Land Cruiser', '6596');
insert into car (id, make, model, price) values (472, 'Porsche', '911', '2317');
insert into car (id, make, model, price) values (473, 'Ford', 'Explorer Sport', '52759');
insert into car (id, make, model, price) values (474, 'Ford', 'F-Series', '26259');
insert into car (id, make, model, price) values (475, 'Toyota', 'Prius', '26');
insert into car (id, make, model, price) values (476, 'Dodge', 'Dakota', '109');
insert into car (id, make, model, price) values (477, 'Hummer', 'H1', '1878');
insert into car (id, make, model, price) values (478, 'Chevrolet', 'Prizm', '539');
insert into car (id, make, model, price) values (479, 'Ford', 'Probe', '95');
insert into car (id, make, model, price) values (480, 'Ford', 'F350', '6241');
insert into car (id, make, model, price) values (481, 'Ford', 'Expedition', '6099');
insert into car (id, make, model, price) values (482, 'Maserati', 'GranTurismo', '849');
insert into car (id, make, model, price) values (483, 'Mercedes-Benz', 'Sprinter', '6');
insert into car (id, make, model, price) values (484, 'Chrysler', 'New Yorker', '20793');
insert into car (id, make, model, price) values (485, 'Toyota', 'Solara', '29480');
insert into car (id, make, model, price) values (486, 'Kia', 'Rio', '6');
insert into car (id, make, model, price) values (487, 'Dodge', 'Ram 3500', '245');
insert into car (id, make, model, price) values (488, 'Pontiac', 'Safari', '692');
insert into car (id, make, model, price) values (489, 'Chevrolet', 'Monte Carlo', '3');
insert into car (id, make, model, price) values (490, 'Saturn', 'VUE', '5730');
insert into car (id, make, model, price) values (491, 'Isuzu', 'i-350', '663');
insert into car (id, make, model, price) values (492, 'Toyota', 'Solara', '1399');
insert into car (id, make, model, price) values (493, 'Volkswagen', 'Passat', '0046');
insert into car (id, make, model, price) values (494, 'Saab', '9-3', '432');
insert into car (id, make, model, price) values (495, 'Chevrolet', 'Silverado 3500', '917');
insert into car (id, make, model, price) values (496, 'Volkswagen', 'Cabriolet', '3662');
insert into car (id, make, model, price) values (497, 'Saturn', 'L-Series', '10364');
insert into car (id, make, model, price) values (498, 'Land Rover', 'Range Rover', '9');
insert into car (id, make, model, price) values (499, 'Chevrolet', 'Monte Carlo', '8');
insert into car (id, make, model, price) values (500, 'Volkswagen', 'New Beetle', '652');
insert into car (id, make, model, price) values (501, 'Porsche', '968', '89');
insert into car (id, make, model, price) values (502, 'Dodge', 'Ram 2500 Club', '3');
insert into car (id, make, model, price) values (503, 'Volkswagen', 'Golf', '050');
insert into car (id, make, model, price) values (504, 'Volkswagen', 'rio', '38');
insert into car (id, make, model, price) values (505, 'Mercedes-Benz', 'SLK-Class', '82627');
insert into car (id, make, model, price) values (506, 'Mitsubishi', 'GTO', '198');
insert into car (id, make, model, price) values (507, 'Chrysler', 'Pacifica', '24');
insert into car (id, make, model, price) values (508, 'Nissan', 'Sentra', '28666');
insert into car (id, make, model, price) values (509, 'Honda', 'Passport', '23');
insert into car (id, make, model, price) values (510, 'Subaru', 'Legacy', '61');
insert into car (id, make, model, price) values (511, 'Ford', 'Taurus', '813');
insert into car (id, make, model, price) values (512, 'Toyota', 'Corolla', '84');
insert into car (id, make, model, price) values (513, 'Citroën', 'SM', '04');
insert into car (id, make, model, price) values (514, 'Ford', 'Crown Victoria', '72941');
insert into car (id, make, model, price) values (515, 'Mazda', 'MPV', '241');
insert into car (id, make, model, price) values (516, 'Chrysler', 'LHS', '598');
insert into car (id, make, model, price) values (517, 'Saab', '9000', '32');
insert into car (id, make, model, price) values (518, 'Honda', 'Prelude', '71');
insert into car (id, make, model, price) values (519, 'Toyota', 'Tacoma', '3658');
insert into car (id, make, model, price) values (520, 'Cadillac', 'DTS', '0');
insert into car (id, make, model, price) values (521, 'Chevrolet', 'Suburban', '0377');
insert into car (id, make, model, price) values (522, 'Toyota', 'Camry', '81126');
insert into car (id, make, model, price) values (523, 'Land Rover', 'Discovery', '65');
insert into car (id, make, model, price) values (524, 'Ford', 'Mustang', '9704');
insert into car (id, make, model, price) values (525, 'Dodge', 'Ram', '84');
insert into car (id, make, model, price) values (526, 'Geo', 'Metro', '4847');
insert into car (id, make, model, price) values (527, 'Honda', 'Element', '52');
insert into car (id, make, model, price) values (528, 'Mazda', 'MPV', '757');
insert into car (id, make, model, price) values (529, 'Nissan', 'Maxima', '326');
insert into car (id, make, model, price) values (530, 'Toyota', 'Celica', '7');
insert into car (id, make, model, price) values (531, 'Mazda', 'Tribute', '5791');
insert into car (id, make, model, price) values (532, 'Subaru', 'Impreza', '3915');
insert into car (id, make, model, price) values (533, 'Mitsubishi', 'Diamante', '3');
insert into car (id, make, model, price) values (534, 'GMC', 'Canyon', '27');
insert into car (id, make, model, price) values (535, 'Honda', 'Pilot', '762');
insert into car (id, make, model, price) values (536, 'Mercedes-Benz', 'SL-Class', '32794');
insert into car (id, make, model, price) values (537, 'Mitsubishi', 'Eclipse', '4527');
insert into car (id, make, model, price) values (538, 'Ford', 'E250', '579');
insert into car (id, make, model, price) values (539, 'Pontiac', 'LeMans', '981');
insert into car (id, make, model, price) values (540, 'Mercedes-Benz', '600SEL', '61');
insert into car (id, make, model, price) values (541, 'Buick', 'Riviera', '1');
insert into car (id, make, model, price) values (542, 'BMW', 'M3', '5');
insert into car (id, make, model, price) values (543, 'GMC', 'Suburban 1500', '9');
insert into car (id, make, model, price) values (544, 'Honda', 'Civic', '7');
insert into car (id, make, model, price) values (545, 'Dodge', 'Stratus', '133');
insert into car (id, make, model, price) values (546, 'Ford', 'F150', '29');
insert into car (id, make, model, price) values (547, 'Volvo', 'C70', '6');
insert into car (id, make, model, price) values (548, 'Acura', 'TL', '1955');
insert into car (id, make, model, price) values (549, 'Dodge', 'Dakota', '7962');
insert into car (id, make, model, price) values (550, 'Mercury', 'Tracer', '8');
insert into car (id, make, model, price) values (551, 'GMC', 'Savana 2500', '158');
insert into car (id, make, model, price) values (552, 'Pontiac', 'Safari', '166');
insert into car (id, make, model, price) values (553, 'Volkswagen', 'Fox', '54');
insert into car (id, make, model, price) values (554, 'Saturn', 'Astra', '28082');
insert into car (id, make, model, price) values (555, 'Buick', 'Park Avenue', '775');
insert into car (id, make, model, price) values (556, 'Nissan', 'Altima', '4');
insert into car (id, make, model, price) values (557, 'Ford', 'Ranger', '5');
insert into car (id, make, model, price) values (558, 'Subaru', 'Outback', '74');
insert into car (id, make, model, price) values (559, 'Honda', 'Odyssey', '9');
insert into car (id, make, model, price) values (560, 'Honda', 'Ridgeline', '62');
insert into car (id, make, model, price) values (561, 'Honda', 'S2000', '4');
insert into car (id, make, model, price) values (562, 'Volvo', 'C70', '15209');
insert into car (id, make, model, price) values (563, 'Toyota', 'Avalon', '644');
insert into car (id, make, model, price) values (564, 'Plymouth', 'Grand Voyager', '89');
insert into car (id, make, model, price) values (565, 'Honda', 'Pilot', '1');
insert into car (id, make, model, price) values (566, 'Dodge', 'Ram 2500', '0056');
insert into car (id, make, model, price) values (567, 'Buick', 'Hearse', '681');
insert into car (id, make, model, price) values (568, 'Buick', 'Century', '650');
insert into car (id, make, model, price) values (569, 'Pontiac', 'Trans Sport', '0106');
insert into car (id, make, model, price) values (570, 'GMC', '3500', '010');
insert into car (id, make, model, price) values (571, 'GMC', '1500 Club Coupe', '8');
insert into car (id, make, model, price) values (572, 'Mercedes-Benz', 'E-Class', '41453');
insert into car (id, make, model, price) values (573, 'Lincoln', 'Continental Mark VII', '75819');
insert into car (id, make, model, price) values (574, 'Honda', 'Accord', '03');
insert into car (id, make, model, price) values (575, 'Audi', 'TT', '72516');
insert into car (id, make, model, price) values (576, 'Honda', 'Odyssey', '106');
insert into car (id, make, model, price) values (577, 'Toyota', 'Prius v', '33');
insert into car (id, make, model, price) values (578, 'Mazda', 'MX-5', '3823');
insert into car (id, make, model, price) values (579, 'Dodge', 'Ram 2500', '2970');
insert into car (id, make, model, price) values (580, 'Chevrolet', 'Corvette', '39');
insert into car (id, make, model, price) values (581, 'Pontiac', 'Grand Prix', '83');
insert into car (id, make, model, price) values (582, 'Lexus', 'IS', '42');
insert into car (id, make, model, price) values (583, 'Mercedes-Benz', 'E-Class', '39612');
insert into car (id, make, model, price) values (584, 'GMC', 'Rally Wagon 3500', '232');
insert into car (id, make, model, price) values (585, 'Mercedes-Benz', 'E-Class', '2');
insert into car (id, make, model, price) values (586, 'Subaru', 'Legacy', '441');
insert into car (id, make, model, price) values (587, 'GMC', '1500', '1');
insert into car (id, make, model, price) values (588, 'Chevrolet', 'Tahoe', '23');
insert into car (id, make, model, price) values (589, 'Ford', 'E350', '826');
insert into car (id, make, model, price) values (590, 'Lexus', 'LX', '75');
insert into car (id, make, model, price) values (591, 'Volvo', 'S70', '51878');
insert into car (id, make, model, price) values (592, 'Chrysler', 'Concorde', '99');
insert into car (id, make, model, price) values (593, 'Mercedes-Benz', 'CL-Class', '70');
insert into car (id, make, model, price) values (594, 'Honda', 'Civic', '8');
insert into car (id, make, model, price) values (595, 'Mercury', 'Sable', '875');
insert into car (id, make, model, price) values (596, 'Jeep', 'Wrangler', '613');
insert into car (id, make, model, price) values (597, 'Honda', 'Odyssey', '72932');
insert into car (id, make, model, price) values (598, 'Honda', 'Civic', '6487');
insert into car (id, make, model, price) values (599, 'Suzuki', 'Grand Vitara', '95');
insert into car (id, make, model, price) values (600, 'Dodge', 'Stratus', '46');
insert into car (id, make, model, price) values (601, 'Pontiac', 'Vibe', '9906');
insert into car (id, make, model, price) values (602, 'Mercedes-Benz', 'W126', '620');
insert into car (id, make, model, price) values (603, 'Mercury', 'Grand Marquis', '72');
insert into car (id, make, model, price) values (604, 'Lincoln', 'MKZ', '507');
insert into car (id, make, model, price) values (605, 'Chevrolet', 'Silverado 2500', '5361');
insert into car (id, make, model, price) values (606, 'BMW', 'M Roadster', '6600');
insert into car (id, make, model, price) values (607, 'Lincoln', 'Town Car', '197');
insert into car (id, make, model, price) values (608, 'Plymouth', 'Voyager', '4707');
insert into car (id, make, model, price) values (609, 'Mazda', 'B-Series Plus', '0');
insert into car (id, make, model, price) values (610, 'Chevrolet', 'TrailBlazer', '472');
insert into car (id, make, model, price) values (611, 'Nissan', '370Z', '42934');
insert into car (id, make, model, price) values (612, 'Chrysler', 'Town & Country', '38');
insert into car (id, make, model, price) values (613, 'Chrysler', 'Fifth Ave', '30069');
insert into car (id, make, model, price) values (614, 'Porsche', '911', '37261');
insert into car (id, make, model, price) values (615, 'Subaru', 'Outback', '29');
insert into car (id, make, model, price) values (616, 'Scion', 'tC', '16387');
insert into car (id, make, model, price) values (617, 'GMC', 'Jimmy', '4');
insert into car (id, make, model, price) values (618, 'Chevrolet', 'Corvette', '18');
insert into car (id, make, model, price) values (619, 'Isuzu', 'i-Series', '72365');
insert into car (id, make, model, price) values (620, 'Mercedes-Benz', 'SLK-Class', '8454');
insert into car (id, make, model, price) values (621, 'Chevrolet', 'Tahoe', '1');
insert into car (id, make, model, price) values (622, 'Dodge', 'Stratus', '94237');
insert into car (id, make, model, price) values (623, 'Isuzu', 'Trooper', '707');
insert into car (id, make, model, price) values (624, 'Ford', 'Focus', '9708');
insert into car (id, make, model, price) values (625, 'Mitsubishi', 'Space', '8532');
insert into car (id, make, model, price) values (626, 'Ferrari', '612 Scaglietti', '573');
insert into car (id, make, model, price) values (627, 'Lincoln', 'LS', '6');
insert into car (id, make, model, price) values (628, 'Land Rover', 'Discovery', '578');
insert into car (id, make, model, price) values (629, 'Buick', 'Coachbuilder', '63168');
insert into car (id, make, model, price) values (630, 'Honda', 'Civic', '35');
insert into car (id, make, model, price) values (631, 'Porsche', '968', '1');
insert into car (id, make, model, price) values (632, 'Chevrolet', 'Silverado Hybrid', '67737');
insert into car (id, make, model, price) values (633, 'Oldsmobile', 'Silhouette', '69');
insert into car (id, make, model, price) values (634, 'Subaru', 'Outback', '67');
insert into car (id, make, model, price) values (635, 'Lexus', 'SC', '081');
insert into car (id, make, model, price) values (636, 'Dodge', 'Nitro', '070');
insert into car (id, make, model, price) values (637, 'Acura', 'Vigor', '838');
insert into car (id, make, model, price) values (638, 'Porsche', '911', '20968');
insert into car (id, make, model, price) values (639, 'Saturn', 'VUE', '5052');
insert into car (id, make, model, price) values (640, 'Audi', 'A8', '0843');
insert into car (id, make, model, price) values (641, 'Geo', 'Prizm', '893');
insert into car (id, make, model, price) values (642, 'Pontiac', 'Bonneville', '47899');
insert into car (id, make, model, price) values (643, 'Nissan', 'Sentra', '8');
insert into car (id, make, model, price) values (644, 'Audi', 'A5', '91');
insert into car (id, make, model, price) values (645, 'Ford', 'Thunderbird', '10728');
insert into car (id, make, model, price) values (646, 'Isuzu', 'i-290', '7977');
insert into car (id, make, model, price) values (647, 'Ford', 'C-MAX Hybrid', '4038');
insert into car (id, make, model, price) values (648, 'Hyundai', 'Santa Fe', '661');
insert into car (id, make, model, price) values (649, 'Mitsubishi', 'Lancer', '8');
insert into car (id, make, model, price) values (650, 'BMW', '5 Series', '67142');
insert into car (id, make, model, price) values (651, 'Lincoln', 'Navigator L', '60776');
insert into car (id, make, model, price) values (652, 'Ford', 'F150', '05443');
insert into car (id, make, model, price) values (653, 'Toyota', 'MR2', '30554');
insert into car (id, make, model, price) values (654, 'Mazda', 'Mazda2', '423');
insert into car (id, make, model, price) values (655, 'Lexus', 'GX', '33');
insert into car (id, make, model, price) values (656, 'Toyota', 'Camry', '6634');
insert into car (id, make, model, price) values (657, 'Hyundai', 'Elantra', '95');
insert into car (id, make, model, price) values (658, 'Spyker', 'C8 Spyder Wide Body', '859');
insert into car (id, make, model, price) values (659, 'Ford', 'Explorer', '3');
insert into car (id, make, model, price) values (660, 'Chevrolet', 'Sportvan G30', '777');
insert into car (id, make, model, price) values (661, 'Cadillac', 'Escalade EXT', '0483');
insert into car (id, make, model, price) values (662, 'Subaru', 'Baja', '329');
insert into car (id, make, model, price) values (663, 'Chevrolet', '1500', '024');
insert into car (id, make, model, price) values (664, 'Mercedes-Benz', 'SLK-Class', '23');
insert into car (id, make, model, price) values (665, 'Volvo', 'C70', '7');
insert into car (id, make, model, price) values (666, 'Jaguar', 'S-Type', '760');
insert into car (id, make, model, price) values (667, 'Jaguar', 'XK Series', '0');
insert into car (id, make, model, price) values (668, 'Alfa Romeo', '164', '836');
insert into car (id, make, model, price) values (669, 'Dodge', 'Ram 3500', '37');
insert into car (id, make, model, price) values (670, 'GMC', 'Sierra', '1');
insert into car (id, make, model, price) values (671, 'Audi', 'Allroad', '67');
insert into car (id, make, model, price) values (672, 'Dodge', 'Caravan', '66129');
insert into car (id, make, model, price) values (673, 'Pontiac', 'Firebird', '67474');
insert into car (id, make, model, price) values (674, 'Lamborghini', 'Gallardo', '56278');
insert into car (id, make, model, price) values (675, 'Dodge', 'Charger', '1913');
insert into car (id, make, model, price) values (676, 'Ford', 'Econoline E150', '492');
insert into car (id, make, model, price) values (677, 'Ford', 'Country', '0938');
insert into car (id, make, model, price) values (678, 'BMW', '745', '31');
insert into car (id, make, model, price) values (679, 'Mercedes-Benz', 'C-Class', '250');
insert into car (id, make, model, price) values (680, 'Kia', 'Sportage', '9860');
insert into car (id, make, model, price) values (681, 'Nissan', 'Quest', '0');
insert into car (id, make, model, price) values (682, 'Toyota', 'Sequoia', '29282');
insert into car (id, make, model, price) values (683, 'Nissan', 'Sentra', '41707');
insert into car (id, make, model, price) values (684, 'Pontiac', 'Sunfire', '1828');
insert into car (id, make, model, price) values (685, 'Daewoo', 'Lanos', '621');
insert into car (id, make, model, price) values (686, 'Land Rover', 'Freelander', '282');
insert into car (id, make, model, price) values (687, 'Audi', 'A6', '844');
insert into car (id, make, model, price) values (688, 'Toyota', 'Corolla', '2505');
insert into car (id, make, model, price) values (689, 'Ford', 'Escape', '43');
insert into car (id, make, model, price) values (690, 'Dodge', 'Ram', '325');
insert into car (id, make, model, price) values (691, 'Nissan', 'Versa', '6791');
insert into car (id, make, model, price) values (692, 'Ford', 'Thunderbird', '1382');
insert into car (id, make, model, price) values (693, 'Hyundai', 'XG350', '80150');
insert into car (id, make, model, price) values (694, 'Volkswagen', 'rio', '416');
insert into car (id, make, model, price) values (695, 'Ford', 'Explorer', '7');
insert into car (id, make, model, price) values (696, 'Lincoln', 'Continental', '4087');
insert into car (id, make, model, price) values (697, 'Nissan', '300ZX', '399');
insert into car (id, make, model, price) values (698, 'Toyota', 'Avalon', '47656');
insert into car (id, make, model, price) values (699, 'Lamborghini', 'Murciélago', '676');
insert into car (id, make, model, price) values (700, 'Infiniti', 'QX', '55');
insert into car (id, make, model, price) values (701, 'Lexus', 'SC', '109');
insert into car (id, make, model, price) values (702, 'Volvo', 'V70', '82');
insert into car (id, make, model, price) values (703, 'Volvo', 'S40', '9');
insert into car (id, make, model, price) values (704, 'Audi', '100', '5717');
insert into car (id, make, model, price) values (705, 'Oldsmobile', 'Silhouette', '2652');
insert into car (id, make, model, price) values (706, 'Mercury', 'Topaz', '70721');
insert into car (id, make, model, price) values (707, 'Mercedes-Benz', '500SL', '42');
insert into car (id, make, model, price) values (708, 'Dodge', 'Ram 2500', '9');
insert into car (id, make, model, price) values (709, 'Subaru', 'Brat', '6');
insert into car (id, make, model, price) values (710, 'Mazda', 'Miata MX-5', '989');
insert into car (id, make, model, price) values (711, 'Chevrolet', 'Silverado 2500', '39721');
insert into car (id, make, model, price) values (712, 'Toyota', 'Sienna', '5326');
insert into car (id, make, model, price) values (713, 'Mercedes-Benz', 'CL-Class', '19038');
insert into car (id, make, model, price) values (714, 'Mercury', 'Sable', '1018');
insert into car (id, make, model, price) values (715, 'Jaguar', 'XJ Series', '29');
insert into car (id, make, model, price) values (716, 'Saab', '900', '6044');
insert into car (id, make, model, price) values (717, 'Kia', 'Sportage', '6');
insert into car (id, make, model, price) values (718, 'Chevrolet', 'Avalanche 1500', '959');
insert into car (id, make, model, price) values (719, 'Acura', 'TL', '4163');
insert into car (id, make, model, price) values (720, 'Mercedes-Benz', 'G-Class', '9655');
insert into car (id, make, model, price) values (721, 'GMC', '1500 Club Coupe', '8050');
insert into car (id, make, model, price) values (722, 'Porsche', '911', '57468');
insert into car (id, make, model, price) values (723, 'Nissan', 'GT-R', '277');
insert into car (id, make, model, price) values (724, 'Volkswagen', 'Eurovan', '53');
insert into car (id, make, model, price) values (725, 'Ford', 'E350', '4');
insert into car (id, make, model, price) values (726, 'Ford', 'Bronco', '0');
insert into car (id, make, model, price) values (727, 'Subaru', 'Forester', '056');
insert into car (id, make, model, price) values (728, 'Mercury', 'Sable', '7');
insert into car (id, make, model, price) values (729, 'Dodge', 'Ram 3500 Club', '922');
insert into car (id, make, model, price) values (730, 'BMW', '525', '94022');
insert into car (id, make, model, price) values (731, 'Volkswagen', 'Cabriolet', '771');
insert into car (id, make, model, price) values (732, 'Chevrolet', 'Corvette', '4');
insert into car (id, make, model, price) values (733, 'Audi', 'A4', '732');
insert into car (id, make, model, price) values (734, 'Toyota', 'Camry Hybrid', '6134');
insert into car (id, make, model, price) values (735, 'Chevrolet', 'Tracker', '4360');
insert into car (id, make, model, price) values (736, 'Mazda', 'MX-3', '53319');
insert into car (id, make, model, price) values (737, 'Nissan', 'Frontier', '485');
insert into car (id, make, model, price) values (738, 'Porsche', '928', '85165');
insert into car (id, make, model, price) values (739, 'Toyota', 'Tacoma', '7772');
insert into car (id, make, model, price) values (740, 'Dodge', 'Ram 3500 Club', '7');
insert into car (id, make, model, price) values (741, 'Mitsubishi', 'GTO', '374');
insert into car (id, make, model, price) values (742, 'Dodge', 'Shadow', '5');
insert into car (id, make, model, price) values (743, 'Mercury', 'Mariner', '5');
insert into car (id, make, model, price) values (744, 'Pontiac', 'Grand Prix', '0082');
insert into car (id, make, model, price) values (745, 'Mazda', 'Mazda5', '897');
insert into car (id, make, model, price) values (746, 'Acura', 'NSX', '4');
insert into car (id, make, model, price) values (747, 'Lexus', 'RX', '44');
insert into car (id, make, model, price) values (748, 'Ford', 'Explorer Sport Trac', '9');
insert into car (id, make, model, price) values (749, 'Mitsubishi', 'Outlander', '392');
insert into car (id, make, model, price) values (750, 'Ford', 'F350', '63');
insert into car (id, make, model, price) values (751, 'Hyundai', 'Sonata', '06');
insert into car (id, make, model, price) values (752, 'GMC', 'Jimmy', '62');
insert into car (id, make, model, price) values (753, 'Buick', 'Regal', '4868');
insert into car (id, make, model, price) values (754, 'Saturn', 'S-Series', '45');
insert into car (id, make, model, price) values (755, 'GMC', 'Jimmy', '29');
insert into car (id, make, model, price) values (756, 'Ford', 'Bronco II', '4960');
insert into car (id, make, model, price) values (757, 'Dodge', 'Ram Van B150', '88');
insert into car (id, make, model, price) values (758, 'Hyundai', 'Tiburon', '99640');
insert into car (id, make, model, price) values (759, 'Nissan', 'Sentra', '1337');
insert into car (id, make, model, price) values (760, 'Infiniti', 'QX', '01614');
insert into car (id, make, model, price) values (761, 'Cadillac', 'Allante', '48133');
insert into car (id, make, model, price) values (762, 'Mercury', 'Montego', '8');
insert into car (id, make, model, price) values (763, 'Chevrolet', 'Malibu', '73442');
insert into car (id, make, model, price) values (764, 'Chevrolet', 'Camaro', '13895');
insert into car (id, make, model, price) values (765, 'Dodge', 'D250 Club', '5');
insert into car (id, make, model, price) values (766, 'Dodge', 'Viper', '2');
insert into car (id, make, model, price) values (767, 'Audi', '4000CS Quattro', '85030');
insert into car (id, make, model, price) values (768, 'GMC', 'Rally Wagon 3500', '10213');
insert into car (id, make, model, price) values (769, 'Mercedes-Benz', 'Sprinter 3500', '792');
insert into car (id, make, model, price) values (770, 'Ford', 'Taurus', '5');
insert into car (id, make, model, price) values (771, 'GMC', 'Sonoma Club Coupe', '57175');
insert into car (id, make, model, price) values (772, 'Chevrolet', 'Monte Carlo', '4');
insert into car (id, make, model, price) values (773, 'Ford', 'Laser', '805');
insert into car (id, make, model, price) values (774, 'Mitsubishi', 'Montero Sport', '4804');
insert into car (id, make, model, price) values (775, 'Chevrolet', 'Suburban 1500', '1409');
insert into car (id, make, model, price) values (776, 'GMC', 'Rally Wagon 3500', '0');
insert into car (id, make, model, price) values (777, 'Mitsubishi', 'Eclipse', '18917');
insert into car (id, make, model, price) values (778, 'Chevrolet', 'Cavalier', '67');
insert into car (id, make, model, price) values (779, 'Porsche', '968', '9928');
insert into car (id, make, model, price) values (780, 'Subaru', 'Legacy', '9');
insert into car (id, make, model, price) values (781, 'Ford', 'Tempo', '79');
insert into car (id, make, model, price) values (782, 'Honda', 'Odyssey', '24146');
insert into car (id, make, model, price) values (783, 'Ford', 'Econoline E250', '0055');
insert into car (id, make, model, price) values (784, 'Audi', 'Coupe GT', '963');
insert into car (id, make, model, price) values (785, 'Audi', 'RS 6', '260');
insert into car (id, make, model, price) values (786, 'Nissan', 'Altima', '2');
insert into car (id, make, model, price) values (787, 'Mazda', 'Tribute', '2');
insert into car (id, make, model, price) values (788, 'Oldsmobile', 'Bravada', '6');
insert into car (id, make, model, price) values (789, 'GMC', 'Sonoma', '50');
insert into car (id, make, model, price) values (790, 'BMW', '3 Series', '82257');
insert into car (id, make, model, price) values (791, 'Lincoln', 'MKX', '3');
insert into car (id, make, model, price) values (792, 'Ford', 'Taurus', '91');
insert into car (id, make, model, price) values (793, 'Kia', 'Rio', '18');
insert into car (id, make, model, price) values (794, 'Ford', 'Probe', '23478');
insert into car (id, make, model, price) values (795, 'Daewoo', 'Nubira', '74048');
insert into car (id, make, model, price) values (796, 'BMW', '3 Series', '707');
insert into car (id, make, model, price) values (797, 'Nissan', 'Armada', '9');
insert into car (id, make, model, price) values (798, 'Aston Martin', 'V8 Vantage', '6');
insert into car (id, make, model, price) values (799, 'Buick', 'Regal', '4550');
insert into car (id, make, model, price) values (800, 'Jeep', 'Commander', '74129');
insert into car (id, make, model, price) values (801, 'Ford', 'E-Series', '948');
insert into car (id, make, model, price) values (802, 'Maserati', 'Karif', '1079');
insert into car (id, make, model, price) values (803, 'Pontiac', 'Firebird', '5');
insert into car (id, make, model, price) values (804, 'Toyota', 'Tacoma', '5');
insert into car (id, make, model, price) values (805, 'Volvo', 'V90', '40677');
insert into car (id, make, model, price) values (806, 'Mercedes-Benz', 'SLK-Class', '29');
insert into car (id, make, model, price) values (807, 'Pontiac', 'Firefly', '20');
insert into car (id, make, model, price) values (808, 'Mazda', 'MX-5', '61');
insert into car (id, make, model, price) values (809, 'GMC', 'Sonoma', '34450');
insert into car (id, make, model, price) values (810, 'Land Rover', 'LR2', '08429');
insert into car (id, make, model, price) values (811, 'Dodge', 'Stratus', '893');
insert into car (id, make, model, price) values (812, 'Honda', 'Civic Si', '7');
insert into car (id, make, model, price) values (813, 'Mazda', '626', '86');
insert into car (id, make, model, price) values (814, 'Cadillac', 'Escalade ESV', '96374');
insert into car (id, make, model, price) values (815, 'GMC', 'Sierra 2500HD', '8');
insert into car (id, make, model, price) values (816, 'Mercedes-Benz', '600SEL', '11');
insert into car (id, make, model, price) values (817, 'Lexus', 'HS', '7443');
insert into car (id, make, model, price) values (818, 'Maybach', '57', '85976');
insert into car (id, make, model, price) values (819, 'Mercedes-Benz', 'S-Class', '71');
insert into car (id, make, model, price) values (820, 'Buick', 'LeSabre', '50');
insert into car (id, make, model, price) values (821, 'Kia', 'Rio', '0');
insert into car (id, make, model, price) values (822, 'Jeep', 'Commander', '18697');
insert into car (id, make, model, price) values (823, 'Cadillac', 'DeVille', '440');
insert into car (id, make, model, price) values (824, 'Ford', 'Flex', '818');
insert into car (id, make, model, price) values (825, 'Chevrolet', 'HHR', '7');
insert into car (id, make, model, price) values (826, 'Mercedes-Benz', 'S-Class', '49994');
insert into car (id, make, model, price) values (827, 'Ford', 'Expedition', '035');
insert into car (id, make, model, price) values (828, 'Lincoln', 'LS', '914');
insert into car (id, make, model, price) values (829, 'Buick', 'Enclave', '5');
insert into car (id, make, model, price) values (830, 'Mitsubishi', 'GTO', '48');
insert into car (id, make, model, price) values (831, 'Ford', 'Expedition', '41');
insert into car (id, make, model, price) values (832, 'Ford', 'Windstar', '35445');
insert into car (id, make, model, price) values (833, 'Ford', 'F350', '9766');
insert into car (id, make, model, price) values (834, 'Mercedes-Benz', '600SEC', '3756');
insert into car (id, make, model, price) values (835, 'Chevrolet', 'G-Series G30', '33');
insert into car (id, make, model, price) values (836, 'Ford', 'Mustang', '85');
insert into car (id, make, model, price) values (837, 'Studebaker', 'Avanti', '5352');
insert into car (id, make, model, price) values (838, 'Chevrolet', 'Express 3500', '6432');
insert into car (id, make, model, price) values (839, 'Chevrolet', 'Silverado 3500', '5');
insert into car (id, make, model, price) values (840, 'Saturn', 'S-Series', '8192');
insert into car (id, make, model, price) values (841, 'Plymouth', 'Voyager', '441');
insert into car (id, make, model, price) values (842, 'Volvo', 'C70', '9751');
insert into car (id, make, model, price) values (843, 'Saturn', 'Relay', '15915');
insert into car (id, make, model, price) values (844, 'Lexus', 'LS', '38');
insert into car (id, make, model, price) values (845, 'Mercedes-Benz', 'SL-Class', '8');
insert into car (id, make, model, price) values (846, 'Audi', 'A8', '42249');
insert into car (id, make, model, price) values (847, 'Plymouth', 'Colt Vista', '05581');
insert into car (id, make, model, price) values (848, 'Land Rover', 'Range Rover', '17');
insert into car (id, make, model, price) values (849, 'Lamborghini', 'Countach', '91271');
insert into car (id, make, model, price) values (850, 'Nissan', 'Altima', '6');
insert into car (id, make, model, price) values (851, 'Mitsubishi', 'Endeavor', '5537');
insert into car (id, make, model, price) values (852, 'Pontiac', 'G5', '7');
insert into car (id, make, model, price) values (853, 'Ford', 'Explorer', '15775');
insert into car (id, make, model, price) values (854, 'Ford', 'Mustang', '9');
insert into car (id, make, model, price) values (855, 'Chrysler', 'Grand Voyager', '21');
insert into car (id, make, model, price) values (856, 'Dodge', 'Caravan', '84');
insert into car (id, make, model, price) values (857, 'Cadillac', 'Seville', '23620');
insert into car (id, make, model, price) values (858, 'Aston Martin', 'DB9', '8338');
insert into car (id, make, model, price) values (859, 'Pontiac', '6000', '9913');
insert into car (id, make, model, price) values (860, 'Kia', 'Spectra', '49794');
insert into car (id, make, model, price) values (861, 'Buick', 'Riviera', '17');
insert into car (id, make, model, price) values (862, 'BMW', 'Z4', '5185');
insert into car (id, make, model, price) values (863, 'Toyota', '4Runner', '54');
insert into car (id, make, model, price) values (864, 'Kia', 'Spectra', '8243');
insert into car (id, make, model, price) values (865, 'Infiniti', 'G', '4470');
insert into car (id, make, model, price) values (866, 'Toyota', 'FJ Cruiser', '2');
insert into car (id, make, model, price) values (867, 'Land Rover', 'Range Rover', '138');
insert into car (id, make, model, price) values (868, 'Mazda', 'MX-5', '18');
insert into car (id, make, model, price) values (869, 'Chevrolet', 'Express 1500', '7');
insert into car (id, make, model, price) values (870, 'Mazda', 'B-Series Plus', '29617');
insert into car (id, make, model, price) values (871, 'Lamborghini', 'Murciélago LP640', '5302');
insert into car (id, make, model, price) values (872, 'Saab', '9-5', '4532');
insert into car (id, make, model, price) values (873, 'Toyota', 'Venza', '90452');
insert into car (id, make, model, price) values (874, 'Ford', 'Excursion', '08929');
insert into car (id, make, model, price) values (875, 'GMC', '2500 Club Coupe', '25637');
insert into car (id, make, model, price) values (876, 'Chevrolet', 'Tahoe', '5');
insert into car (id, make, model, price) values (877, 'Jeep', 'Liberty', '595');
insert into car (id, make, model, price) values (878, 'Lexus', 'IS-F', '97');
insert into car (id, make, model, price) values (879, 'Ford', 'Escort', '85715');
insert into car (id, make, model, price) values (880, 'Land Rover', 'Defender 110', '07985');
insert into car (id, make, model, price) values (881, 'Honda', 'Insight', '11');
insert into car (id, make, model, price) values (882, 'Buick', 'Riviera', '75');
insert into car (id, make, model, price) values (883, 'Maserati', 'Coupe', '8');
insert into car (id, make, model, price) values (884, 'Ford', 'Econoline E150', '3');
insert into car (id, make, model, price) values (885, 'Mitsubishi', 'L300', '00838');
insert into car (id, make, model, price) values (886, 'Bentley', 'Continental Flying Spur', '67154');
insert into car (id, make, model, price) values (887, 'BMW', '600', '69683');
insert into car (id, make, model, price) values (888, 'Infiniti', 'QX56', '34245');
insert into car (id, make, model, price) values (889, 'Audi', '4000s', '9332');
insert into car (id, make, model, price) values (890, 'Rolls-Royce', 'Phantom', '51460');
insert into car (id, make, model, price) values (891, 'BMW', 'M Roadster', '5353');
insert into car (id, make, model, price) values (892, 'Subaru', 'Impreza WRX', '5');
insert into car (id, make, model, price) values (893, 'Pontiac', 'Montana', '27');
insert into car (id, make, model, price) values (894, 'Chevrolet', 'G-Series 1500', '4');
insert into car (id, make, model, price) values (895, 'Lexus', 'CT', '229');
insert into car (id, make, model, price) values (896, 'Infiniti', 'QX', '187');
insert into car (id, make, model, price) values (897, 'Audi', 'Q7', '07025');
insert into car (id, make, model, price) values (898, 'Buick', 'Century', '3');
insert into car (id, make, model, price) values (899, 'Mercedes-Benz', 'W201', '162');
insert into car (id, make, model, price) values (900, 'Ford', 'Expedition', '2747');
insert into car (id, make, model, price) values (901, 'Pontiac', 'LeMans', '22');
insert into car (id, make, model, price) values (902, 'GMC', 'Yukon XL 2500', '0');
insert into car (id, make, model, price) values (903, 'Isuzu', 'Hombre Space', '0');
insert into car (id, make, model, price) values (904, 'Volkswagen', 'Touareg', '11598');
insert into car (id, make, model, price) values (905, 'Audi', '4000CS Quattro', '85061');
insert into car (id, make, model, price) values (906, 'Suzuki', 'SJ', '2');
insert into car (id, make, model, price) values (907, 'Pontiac', 'Grand Prix', '77647');
insert into car (id, make, model, price) values (908, 'Audi', '5000S', '543');
insert into car (id, make, model, price) values (909, 'Cadillac', 'DeVille', '19533');
insert into car (id, make, model, price) values (910, 'GMC', 'Envoy', '6');
insert into car (id, make, model, price) values (911, 'Mazda', '929', '4646');
insert into car (id, make, model, price) values (912, 'Ford', 'Mustang', '497');
insert into car (id, make, model, price) values (913, 'Buick', 'Rainier', '95');
insert into car (id, make, model, price) values (914, 'Honda', 'Civic Si', '852');
insert into car (id, make, model, price) values (915, 'Mercedes-Benz', 'CL-Class', '6');
insert into car (id, make, model, price) values (916, 'Pontiac', 'LeMans', '5');
insert into car (id, make, model, price) values (917, 'Volkswagen', 'GTI', '67');
insert into car (id, make, model, price) values (918, 'Audi', 'A4', '766');
insert into car (id, make, model, price) values (919, 'Volvo', 'C70', '197');
insert into car (id, make, model, price) values (920, 'Volkswagen', 'Cabriolet', '46');
insert into car (id, make, model, price) values (921, 'Audi', 'R8', '5');
insert into car (id, make, model, price) values (922, 'Ford', 'Explorer Sport Trac', '602');
insert into car (id, make, model, price) values (923, 'Suzuki', 'Swift', '87');
insert into car (id, make, model, price) values (924, 'Acura', 'Integra', '41');
insert into car (id, make, model, price) values (925, 'Maybach', '57S', '0');
insert into car (id, make, model, price) values (926, 'Lexus', 'LS', '06');
insert into car (id, make, model, price) values (927, 'Nissan', 'Pathfinder', '698');
insert into car (id, make, model, price) values (928, 'Mercury', 'Grand Marquis', '726');
insert into car (id, make, model, price) values (929, 'Lamborghini', 'Murciélago', '12772');
insert into car (id, make, model, price) values (930, 'Dodge', 'Ram Van B250', '3');
insert into car (id, make, model, price) values (931, 'Mazda', '626', '666');
insert into car (id, make, model, price) values (932, 'Chevrolet', 'G-Series G20', '32');
insert into car (id, make, model, price) values (933, 'Kia', 'Optima', '81465');
insert into car (id, make, model, price) values (934, 'Honda', 'Civic GX', '4');
insert into car (id, make, model, price) values (935, 'Nissan', 'Altima', '981');
insert into car (id, make, model, price) values (936, 'Lexus', 'LX', '92507');
insert into car (id, make, model, price) values (937, 'Isuzu', 'Trooper', '55');
insert into car (id, make, model, price) values (938, 'Ford', 'Bronco II', '6');
insert into car (id, make, model, price) values (939, 'Toyota', 'Celica', '56243');
insert into car (id, make, model, price) values (940, 'Cadillac', 'CTS', '85002');
insert into car (id, make, model, price) values (941, 'Mazda', 'Mazdaspeed 3', '2094');
insert into car (id, make, model, price) values (942, 'Mercury', 'Cougar', '62059');
insert into car (id, make, model, price) values (943, 'Ferrari', '599 GTB Fiorano', '173');
insert into car (id, make, model, price) values (944, 'Volkswagen', 'Jetta', '09');
insert into car (id, make, model, price) values (945, 'Audi', 'RS6', '97550');
insert into car (id, make, model, price) values (946, 'Hummer', 'H2', '42178');
insert into car (id, make, model, price) values (947, 'Infiniti', 'G25', '8');
insert into car (id, make, model, price) values (948, 'Mercury', 'Sable', '01433');
insert into car (id, make, model, price) values (949, 'Volkswagen', 'Cabriolet', '2');
insert into car (id, make, model, price) values (950, 'Pontiac', 'Grand Am', '46');
insert into car (id, make, model, price) values (951, 'Isuzu', 'Rodeo', '969');
insert into car (id, make, model, price) values (952, 'Jeep', 'Cherokee', '705');
insert into car (id, make, model, price) values (953, 'Maserati', 'Spyder', '61');
insert into car (id, make, model, price) values (954, 'BMW', '550', '860');
insert into car (id, make, model, price) values (955, 'Hyundai', 'Elantra', '9335');
insert into car (id, make, model, price) values (956, 'BMW', 'X6', '98');
insert into car (id, make, model, price) values (957, 'Honda', 'Ridgeline', '3');
insert into car (id, make, model, price) values (958, 'Oldsmobile', 'Cutlass Supreme', '2504');
insert into car (id, make, model, price) values (959, 'Volkswagen', 'Jetta', '82');
insert into car (id, make, model, price) values (960, 'Aston Martin', 'DB9', '63');
insert into car (id, make, model, price) values (961, 'Volkswagen', 'Jetta', '59');
insert into car (id, make, model, price) values (962, 'Honda', 'Element', '7');
insert into car (id, make, model, price) values (963, 'Nissan', '370Z', '7');
insert into car (id, make, model, price) values (964, 'Lexus', 'LX', '9');
insert into car (id, make, model, price) values (965, 'Aston Martin', 'Vantage', '532');
insert into car (id, make, model, price) values (966, 'Volkswagen', 'New Beetle', '988');
insert into car (id, make, model, price) values (967, 'Buick', 'Rainier', '4');
insert into car (id, make, model, price) values (968, 'Volkswagen', 'GTI', '0833');
insert into car (id, make, model, price) values (969, 'Mitsubishi', 'Chariot', '8559');
insert into car (id, make, model, price) values (970, 'Lexus', 'IS', '51047');
insert into car (id, make, model, price) values (971, 'Pontiac', 'Montana', '2443');
insert into car (id, make, model, price) values (972, 'Oldsmobile', 'Silhouette', '399');
insert into car (id, make, model, price) values (973, 'Volvo', 'S60', '63970');
insert into car (id, make, model, price) values (974, 'Audi', 'A4', '456');
insert into car (id, make, model, price) values (975, 'Toyota', 'Echo', '92044');
insert into car (id, make, model, price) values (976, 'Mercedes-Benz', 'CLK-Class', '71');
insert into car (id, make, model, price) values (977, 'Cadillac', 'Escalade EXT', '95964');
insert into car (id, make, model, price) values (978, 'Porsche', '928', '556');
insert into car (id, make, model, price) values (979, 'Dodge', 'Dakota Club', '61');
insert into car (id, make, model, price) values (980, 'Subaru', 'Forester', '86');
insert into car (id, make, model, price) values (981, 'Volvo', 'XC90', '0800');
insert into car (id, make, model, price) values (982, 'Volkswagen', 'Jetta', '453');
insert into car (id, make, model, price) values (983, 'Mitsubishi', 'GTO', '46');
insert into car (id, make, model, price) values (984, 'Lexus', 'SC', '545');
insert into car (id, make, model, price) values (985, 'Subaru', 'Brat', '8363');
insert into car (id, make, model, price) values (986, 'Mercury', 'Sable', '3');
insert into car (id, make, model, price) values (987, 'GMC', 'Sonoma', '68634');
insert into car (id, make, model, price) values (988, 'Honda', 'Element', '76968');
insert into car (id, make, model, price) values (989, 'Infiniti', 'G', '7');
insert into car (id, make, model, price) values (990, 'Buick', 'Skylark', '644');
insert into car (id, make, model, price) values (991, 'Ford', 'E350', '1');
insert into car (id, make, model, price) values (992, 'Nissan', 'Maxima', '742');
insert into car (id, make, model, price) values (993, 'Dodge', 'Ram 1500', '4298');
insert into car (id, make, model, price) values (994, 'Ford', 'Contour', '0');
insert into car (id, make, model, price) values (995, 'Volkswagen', 'Passat', '7878');
insert into car (id, make, model, price) values (996, 'Dodge', 'Ram 2500', '4');
insert into car (id, make, model, price) values (997, 'Scion', 'xA', '2395');
insert into car (id, make, model, price) values (998, 'Mazda', 'Miata MX-5', '0877');
insert into car (id, make, model, price) values (999, 'Isuzu', 'Hombre', '01447');
insert into car (id, make, model, price) values (1000, 'GMC', 'Yukon', '91');
